import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Hearder";
import Footer from "@/Components/Footer";
import { Providers } from "@/Redux/Provider";
import InitUser from "@/Redux/InitUsers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AZshop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <InitUser/>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
